# This workflow is used to build and test the Java project using GitHub Actions (CI/CD).
name: Java CI

# Triggers the workflow on push or pull request events for the main branch and feature branches.
on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs.
jobs:
  build_and_test:
    # Specifies the type of runner (virtual machine) the job will run on.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out the repository code.
      - uses: actions/checkout@v4

      # Step 2: Sets up the Java Development Kit (JDK) 21.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Grant execute permission to the Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Run tests and build the project using the Gradle wrapper.
      - name: Run tests and build with Gradle
        run: ./gradlew clean build